SELECT
	ETE.EVEN_THEREA_ERROR_ID ID,
	ETE.CATEGORY_6 DESCRIPTION,
	ETE.SUB_CATEGORY_4 SUBCAT,
	-- COMPANY_1_1.DESCRIPTION COMPANY,
    COMPANY_1.DESCRIPTION COMPANY_1_DESCRIPTION,
	DEPARTMENT.DEPARTMENT_NAME DIV_DEPART_NAME,
	EVENT_THREAT_ERROR.DESCRIPTION EVTHER_TYPE,
	BOOLEAN_VALUES.DESCRIPTION DISABLED,
	ETE.POSITION POS
    
FROM EXTERNAL_DATA.EVENT_THEREAT_ERROR ETE
LEFT JOIN ENGINE.BOOLEAN_VALUES BOOLEAN_VALUES ON (ETE.DISABLED_ID = BOOLEAN_VALUES.VALUE )
LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1 ON (ETE.COMPANY_3_ID = COMPANY_1.COMPANY_1_ID )
LEFT JOIN LOOKUPS.EVENT_THREAT_ERROR EVENT_THREAT_ERROR ON (ETE.EVENT_THREAT_ERROR_ID = EVENT_THREAT_ERROR.EVENT_THREAT_ERROR_ID )
LEFT JOIN EXTERNAL_DATA.COMPANY COMPANY_2 ON (ETE.EVEN_THEREA_ERROR_ID = COMPANY_2.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1_1 ON (COMPANY_2.COMPANY_ID = COMPANY_1_1.COMPANY_1_ID )
LEFT JOIN EXTERNAL_DATA.DIVISION_DEPARTMENT DIVISION_DEPARTMENT ON (ETE.EVEN_THEREA_ERROR_ID = DIVISION_DEPARTMENT.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.DEPARTMENT DEPARTMENT ON (DIVISION_DEPARTMENT.DIVISION_DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID )

where ETE.DISABLED_ID = 0
AND COMPANY_1_1.DESCRIPTION = 'AMC'
AND DEPARTMENT.DEPARTMENT_NAME = ''
AND  EVENT_THREAT_ERROR.DESCRIPTION = 'THREAT'
GROUP BY ETE.CATEGORY_6 
ORDER BY ETE.POSITION , ETE.CATEGORY_6

;

SELECT
EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID ID,
COMPANY_1.DESCRIPTION COMPANY,
BOOLEAN_VALUES.DESCRIPTION DISABLED,
DEPARTMENT.DEPARTMENT_NAME DEPART_NAME,
EVENT_THREAT_ERROR.DESCRIPTION EVTHER_TYPE,
EVENT_THEREAT_ERROR.CATEGORY_6 CAT,
EVENT_THEREAT_ERROR.SUB_CATEGORY_4 SUBCAT,
EVENT_THEREAT_ERROR.POSITION POS

FROM EXTERNAL_DATA.EVENT_THEREAT_ERROR EVENT_THEREAT_ERROR
LEFT JOIN EXTERNAL_DATA.COMPANY COMPANY_2 ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = COMPANY_2.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1 ON (COMPANY_2.COMPANY_ID = COMPANY_1.COMPANY_1_ID )
LEFT JOIN ENGINE.BOOLEAN_VALUES BOOLEAN_VALUES ON (EVENT_THEREAT_ERROR.DISABLED_ID = BOOLEAN_VALUES.VALUE )
LEFT JOIN EXTERNAL_DATA.DIVISION_DEPARTMENT DIVISION_DEPARTMENT ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = DIVISION_DEPARTMENT.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.DEPARTMENT DEPARTMENT ON (DIVISION_DEPARTMENT.DIVISION_DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID )
LEFT JOIN LOOKUPS.EVENT_THREAT_ERROR EVENT_THREAT_ERROR ON (EVENT_THEREAT_ERROR.EVENT_THREAT_ERROR_ID = EVENT_THREAT_ERROR.EVENT_THREAT_ERROR_ID )


where EVENT_THEREAT_ERROR.DISABLED_ID = 0
AND COMPANY_1.DESCRIPTION = 'AMC'
AND DEPARTMENT.DEPARTMENT_NAME = 'Air Medical : Operations'
AND  EVENT_THREAT_ERROR.DESCRIPTION = 'THREAT'
GROUP BY EVENT_THEREAT_ERROR.CATEGORY_6 
ORDER BY EVENT_THEREAT_ERROR.POSITION , EVENT_THEREAT_ERROR.CATEGORY_6
;


SELECT
		EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID ID,
		EVENT_THEREAT_ERROR.CATEGORY_6 DESCRIPTION,
		EVENT_THEREAT_ERROR.SUB_CATEGORY_4 SUBCAT,
		COMPANY_1_1.DESCRIPTION COMPANY,
		DEPARTMENT.DEPARTMENT_NAME DIV_DEPART_NAME,
		EVENT_THREAT_ERROR.DESCRIPTION EVTHER_TYPE,
		BOOLEAN_VALUES.DESCRIPTION DISABLED,
		EVENT_THEREAT_ERROR.POSITION POS

	FROM EXTERNAL_DATA.EVENT_THEREAT_ERROR EVENT_THEREAT_ERROR
		LEFT JOIN ENGINE.BOOLEAN_VALUES BOOLEAN_VALUES ON (EVENT_THEREAT_ERROR.DISABLED_ID = BOOLEAN_VALUES.VALUE )
		LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1 ON (EVENT_THEREAT_ERROR.COMPANY_3_ID = COMPANY_1.COMPANY_1_ID )
		LEFT JOIN LOOKUPS.EVENT_THREAT_ERROR EVENT_THREAT_ERROR ON (EVENT_THEREAT_ERROR.EVENT_THREAT_ERROR_ID = EVENT_THREAT_ERROR.EVENT_THREAT_ERROR_ID )
		LEFT JOIN EXTERNAL_DATA.COMPANY COMPANY_2 ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = COMPANY_2.EVEN_THEREA_ERROR_ID )
		LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1_1 ON (COMPANY_2.COMPANY_ID = COMPANY_1_1.COMPANY_1_ID )
		LEFT JOIN EXTERNAL_DATA.DIVISION_DEPARTMENT DIVISION_DEPARTMENT ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = DIVISION_DEPARTMENT.EVEN_THEREA_ERROR_ID )
		LEFT JOIN LOOKUPS.DEPARTMENT DEPARTMENT ON (DIVISION_DEPARTMENT.DIVISION_DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID )
		WHERE EVENT_THEREAT_ERROR.disabled_id = 0 
		
	AND 	COMPANY_1.DESCRIPTION  = 'AMC'  AND DEPARTMENT.DEPARTMENT_NAME = 'Air Medical : Operations' AND  EVENT_THEREAT_ERROR.CATEGORY_6 ='Other' 		group by ORDER BY EVENT_THEREAT_ERROR.POSITION,   EVENT_THEREAT_ERROR.CATEGORY_6