select  COM.DESCRIPTION COMPANY, ETE.CATEGORY_6 DESCRIPTION , IFNULL(ETE.POSITION, 0) POS, ETE.EVEN_THEREA_ERROR_ID ID
		from external_data.event_thereat_error ETE
		left join LOOKUPS.COMPANY_1 comp on ( ETE.COMPANY_3_ID = comp.COMPANY_1_ID)
		left join LOOKUPS.ORG ORG on ( ETE.DIVISION_ID = ORG.ORG_ID)
        left join lookups.division divi on ( ETE.division_id = divi.division_id )
        left join lookups.company_1 COM on ( ETE.COMPANY_3_ID = com.COMPANY_1_ID )
        LEFT JOIN LOOKUPS.DEPARTMENT DEPART ON (ETE.DIVISION_DEPARTMENT_ID = DEPART.DEPARTMENT_ID )
         order by ETE.EVEN_THEREA_ERROR_ID
        
        ;

SELECT
EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID ID,
EVENT_THEREAT_ERROR.CATEGORY_6 CAT,
EVENT_THEREAT_ERROR.SUB_CATEGORY_4 DESCRIPTION,

COMPANY_1_1.DESCRIPTION COMPANY,
DEPARTMENT.DEPARTMENT_NAME DIV_DEPART_NAME,
EVENT_THREAT_ERROR.DESCRIPTION EVTHER_TYPE,
BOOLEAN_VALUES.DESCRIPTION DISABLED,
EVENT_THEREAT_ERROR.POSITION POS

FROM EXTERNAL_DATA.EVENT_THEREAT_ERROR EVENT_THEREAT_ERROR
LEFT JOIN ENGINE.BOOLEAN_VALUES BOOLEAN_VALUES ON (EVENT_THEREAT_ERROR.DISABLED_ID = BOOLEAN_VALUES.VALUE )
LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1 ON (EVENT_THEREAT_ERROR.COMPANY_3_ID = COMPANY_1.COMPANY_1_ID )
LEFT JOIN LOOKUPS.EVENT_THREAT_ERROR EVENT_THREAT_ERROR ON (EVENT_THEREAT_ERROR.EVENT_THREAT_ERROR_ID = EVENT_THREAT_ERROR.EVENT_THREAT_ERROR_ID )
LEFT JOIN EXTERNAL_DATA.COMPANY COMPANY_2 ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = COMPANY_2.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1_1 ON (COMPANY_2.COMPANY_ID = COMPANY_1_1.COMPANY_1_ID )
LEFT JOIN EXTERNAL_DATA.DIVISION_DEPARTMENT DIVISION_DEPARTMENT ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = DIVISION_DEPARTMENT.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.DEPARTMENT DEPARTMENT ON (DIVISION_DEPARTMENT.DIVISION_DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID )
ORDER BY POS, DESCRIPTION
;


SELECT
EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID EVEN_THEREA_ERROR_ID,
EVENT_THEREAT_ERROR.CATEGORY_6 EVENT_THEREAT_ERROR_CATEGORY_6,
COMPANY_1.DESCRIPTION COMPANY_1_DESCRIPTION,
EVENT_THEREAT_ERROR.DATE_5 EVENT_THEREAT_ERROR_DATE_5,
BOOLEAN_VALUES.DESCRIPTION BOOLEAN_VALUES_DESCRIPTION,
DEPARTMENT.DEPARTMENT_NAME DEPARTMENT_DEPARTMENT_NAME,
EVENT_THREAT_ERROR.DESCRIPTION EVENT_THREAT_ERROR_DESCRIPTION,
EVENT_THEREAT_ERROR.POSITION EVENT_THEREAT_ERROR_POSITION,
EVENT_THEREAT_ERROR.SUB_CATEGORY_4 EVEN_THEREA_ERRO_SU_CATEGORY_4

FROM EXTERNAL_DATA.EVENT_THEREAT_ERROR EVENT_THEREAT_ERROR
LEFT JOIN EXTERNAL_DATA.COMPANY COMPANY_2 ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = COMPANY_2.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.COMPANY_1 COMPANY_1 ON (COMPANY_2.COMPANY_ID = COMPANY_1.COMPANY_1_ID )
LEFT JOIN ENGINE.BOOLEAN_VALUES BOOLEAN_VALUES ON (EVENT_THEREAT_ERROR.DISABLED_ID = BOOLEAN_VALUES.VALUE )
LEFT JOIN EXTERNAL_DATA.DIVISION_DEPARTMENT DIVISION_DEPARTMENT ON (EVENT_THEREAT_ERROR.EVEN_THEREA_ERROR_ID = DIVISION_DEPARTMENT.EVEN_THEREA_ERROR_ID )
LEFT JOIN LOOKUPS.DEPARTMENT DEPARTMENT ON (DIVISION_DEPARTMENT.DIVISION_DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID )
LEFT JOIN LOOKUPS.EVENT_THREAT_ERROR EVENT_THREAT_ERROR ON (EVENT_THEREAT_ERROR.EVENT_THREAT_ERROR_ID = EVENT_THREAT_ERROR.EVENT_THREAT_ERROR_ID )