SELECT
IEP_CAPA.IEP_CAPA_ID IEP_CAPA_ID,
PHASE_SETTINGS.DISPLAY_NAME PHASE_SETTINGS_DISPLAY_NAME,
IEP_CAPA.ETQ$NUMBER IEP_CAPA_ETQ$NUMBER,
USER_SETTINGS_1.DISPLAY_NAME USER_SETTINGS_1_DISPLAY_NAME,
IEP_CAPA.DATE IEP_CAPA_DATE,
SOURCE_1.DESCRIPTION SOURCE_1_DESCRIPTION,
IEP_CAPA.SUBJECT_1 IEP_CAPA_SUBJECT_1,
IEP_CAPA.CAPA_ISSUER IEP_CAPA_CAPA_ISSUER,
INITIAL_RAC_1.DESCRIPTION INITIAL_RAC_1_DESCRIPTION,
IEP_CAPA.INITIAL_RAC_COLOR IEP_CAPA_INITIAL_RAC_COLOR,
INITIAL_SEVERITY_1.DESCRIPTION INITIAL_SEVERITY_1_DESCRIPTION,
INITIAL_PROBABILITY_1.DESCRIPTION INITIA_PROBABILIT_1_DESCRIPTIO,
group_concat(LOCATION_PROFILE_1.HIERARCHICAL_NAME separator '\n\n') as LOCATI_PROFI_1_HIERARCHICA_NAM,
SUBJECT_MATTER_1.DESCRIPTION SUBJECT_MATTER_1_DESCRIPTION,
IEP_CAPA.RISK_ITEM_COPY IEP_CAPA_RISK_ITEM_COPY,
IEP_CAPA.IMPACT_COPY IEP_CAPA_IMPACT_COPY,
RISK_MGMT_EVALUATION_1.DESCRIPTION RIS_MGM_EVALUATIO_1_DESCRIPTIO,
IEP_CAPA.ETQ$CREATED_DATE IEP_CAPA_ETQ$CREATED_DATE,
IEP_CAPA.DUE_DATE_1 IEP_CAPA_DUE_DATE_1,
IEP_CAPA.INITIAL_RESPONSE_DATE IEP_CAPA_INITIAL_RESPONSE_DATE,
DATEDIFF(IEP_CAPA.INITIAL_RESPONSE_DATE,IEP_CAPA.ETQ$CREATED_DATE) as DATE_DIFF,
if( IEP_CAPA.INITIAL_RESPONSE_DATE>IEP_CAPA.ETQ$CREATED_DATE,'common/images/red-sad.png','common/images/blank.png') as CAPA_LATE,
IEP_CAPA.INITIAL_COLOR 		IEP_CAPA_INITIAL_COLOR,
BOOLEAN_VALUES_1.DESCRIPTION BOOLEAN_VALUES_1_DESCRIPTION,
IEP_CAPA.DESCRIPTION_1 IEP_CAPA_DESCRIPTION_1

FROM
CORRACT.IEP_CAPA IEP_CAPA
LEFT JOIN
ENGINE.PHASE_SETTINGS PHASE_SETTINGS ON (IEP_CAPA.ETQ$CURRENT_PHASE = PHASE_SETTINGS.PHASE_ID )

LEFT JOIN
CORRACT.ETQ$IEP_CAPA_ASN ETQ$IEP_CAPA_ASN_1 ON (IEP_CAPA.IEP_CAPA_ID = ETQ$IEP_CAPA_ASN_1.IEP_CAPA_ID )

LEFT JOIN
ENGINE.USER_SETTINGS USER_SETTINGS_1 ON (ETQ$IEP_CAPA_ASN_1.ETQ$ASSIGNED = USER_SETTINGS_1.USER_ID )

LEFT JOIN
LOOKUPS.SOURCE SOURCE_1 ON (IEP_CAPA.SOURCE_ID = SOURCE_1.SOURCE_ID )

LEFT JOIN
LOOKUPS.INITIAL_RAC INITIAL_RAC_1 ON (IEP_CAPA.INITIAL_RAC_ID = INITIAL_RAC_1.INITIAL_RAC_ID )

LEFT JOIN
LOOKUPS.INITIAL_SEVERITY INITIAL_SEVERITY_1 ON (IEP_CAPA.SEVERITY_COPY_ID = INITIAL_SEVERITY_1.INITIAL_SEVERITY_ID )

LEFT JOIN
LOOKUPS.INITIAL_PROBABILITY INITIAL_PROBABILITY_1 ON (IEP_CAPA.PROBABILITY_COPY_ID = INITIAL_PROBABILITY_1.INITIAL_PROBABILITY_ID )

LEFT JOIN
CORRACT.ETQ$IEP_CAPA_LOCS ETQ$IEP_CAPA_LOCS_1 ON (IEP_CAPA.IEP_CAPA_ID = ETQ$IEP_CAPA_LOCS_1.IEP_CAPA_ID )

LEFT JOIN
DATACENTER.LOCATION_PROFILE LOCATION_PROFILE_1 ON (ETQ$IEP_CAPA_LOCS_1.ETQ$LOCATIONS_ID = LOCATION_PROFILE_1.LOCATION_PROFILE_ID )

LEFT JOIN
LOOKUPS.SUBJECT_MATTER SUBJECT_MATTER_1 ON (IEP_CAPA.SUBJECT_MATTER_ID = SUBJECT_MATTER_1.SUBJECT_MATTER_ID )

LEFT JOIN
LOOKUPS.RISK_MGMT_EVALUATION RISK_MGMT_EVALUATION_1 ON (IEP_CAPA.RISK_MGMT_EVALUATION_ID = RISK_MGMT_EVALUATION_1.RISK_MGMT_EVALUATION_ID )

LEFT JOIN
ENGINE.BOOLEAN_VALUES BOOLEAN_VALUES_1 ON (IEP_CAPA.IEC_FACILITATED_ID = BOOLEAN_VALUES_1.VALUE )

WHERE
PHASE_SETTINGS.PHASE_TYPE NOT IN (3) 
GROUP BY IEP_CAPA.IEP_CAPA_ID,IEP_CAPA.DESCRIPTION_1