select 
CKL.CHECKLIST_DOCUMENT_ID CHECKLIST_DOCUMENT_ID,
CKL.CHECKLIST_PROFILE_NAME CKL_NAME,
CKL.DISPLAY_NAME USER_NAME,
CKL.ASGN_NAME _NAME,
CKL.PHASE_NAME PHASE_NAME,
RIGHT( 	LOC.HIERARCHICAL_NAME, 	LENGTH( LOC.HIERARCHICAL_NAME) - LOCATE(":", LOC.HIERARCHICAL_NAME) 	)	HIER_NAME,
LEFT(LOC.HIERARCHICAL_NAME , 	LOCATE(":",  LOC.HIERARCHICAL_NAME)-1)	 REGION,
DATE_FORMAT(CKL.ETQ$CREATED_DATE,  '%b %d, %Y' )  CREATE_DATE,
DATE_FORMAT(CKL.ETQ$COMPLETED_DATE,  '%b %d, %Y' )  COMPLETE_DATE

FROM		DATACENTER.LOCATION_PROFILE LOC
LEFT JOIN( 
	SELECT 
		CHECKLIST.CHECKLIST_DOCUMENT_ID CHECKLIST_DOCUMENT_ID,
		AUDIT_DOCUMENT.AUDIT_TYPE AUDIT_DOCUMENT_AUDIT_TYPE,
		CK_PROFILE.CHECKLIST_PROFILE_NAME CHECKLIST_PROFILE_NAME,
		CHECKLIST.ETQ$CREATED_DATE ETQ$CREATED_DATE,
		CHECKLIST.ETQ$COMPLETED_DATE ETQ$COMPLETED_DATE,
		CHECKLIST_LOCS.ETQ$LOCATIONS_ID,
		USR.DISPLAY_NAME DISPLAY_NAME,
		USER_1.DISPLAY_NAME ASGN_NAME,
		PHASE.DISPLAY_NAME PHASE_NAME
		FROM AUDITS.CHECKLIST_DOCUMENT 	CHECKLIST
		LEFT JOIN AUDITS.AUDIT_DOCUMENT AUDIT_DOCUMENT ON (CHECKLIST.AUDIT_DOCUMENT_ID = AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID )
		LEFT JOIN AUDITS.CHECKLIST_PROFILE CK_PROFILE ON (CHECKLIST.CHECKLIST_TYPE = CK_PROFILE.CHECKLIST_PROFILE_ID )
		LEFT JOIN ENGINE.USER_SETTINGS 	USR ON (CHECKLIST.ETQ$AUTHOR = USR.USER_ID )
		LEFT JOIN AUDITS.ETQ$CHECKLIST_DOCUMENT_ASN ASGN ON (CHECKLIST.CHECKLIST_DOCUMENT_ID = ASGN.CHECKLIST_DOCUMENT_ID )
		LEFT JOIN ENGINE.USER_SETTINGS USER_1 ON (ASGN.ETQ$ASSIGNED = USER_1.USER_ID )
		LEFT JOIN AUDITS.ETQ$CHECKLIST_DOCUMENT_LOCS 	CHECKLIST_LOCS ON (CHECKLIST.CHECKLIST_DOCUMENT_ID = CHECKLIST_LOCS.CHECKLIST_DOCUMENT_ID )
		LEFT JOIN ENGINE.PHASE_SETTINGS PHASE ON (CHECKLIST.ETQ$CURRENT_PHASE = PHASE.PHASE_ID )
) CKL ON LOC.LOCATION_PROFILE_ID = CKL.ETQ$LOCATIONS_ID
WHERE    LOC.DISABLED  = 0 
AND LOC.HIERARCHICAL_NAME NOT LIKE  "Sundance%" 
AND LOC.HIERARCHICAL_NAME NOT LIKE  "Training Location%" 
AND LOC.HIERARCHICAL_NAME NOT LIKE "%Fuel Facility%" 
AND LOC.HIERARCHICAL_NAME NOT LIKE  "Vendor%" 
AND LOC.HIERARCHICAL_NAME NOT LIKE  "Corp%" 
AND LOC.HIERARCHICAL_NAME NOT LIKE  "%Maintenance%" 
AND  CKL.CHECKLIST_PROFILE_NAME LIKE "BSA 2nd Quarter 2015 MX%"
GROUP BY LOC.LOCATION_PROFILE_ID














