SELECT
AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID AUDIT_DOCUMENT_ID,
RIGHT( 	LOCATION_PROFILE.HIERARCHICAL_NAME, 	LENGTH( LOCATION_PROFILE.HIERARCHICAL_NAME) - LOCATE(":", LOCATION_PROFILE.HIERARCHICAL_NAME) 	)	LOCATIO_PROFIL_HIERARCHICA_NAM,
DATE_FORMAT(AUDIT_DOCUMENT.ETQ$CREATED_DATE ,  '%b %d, %Y' ) 		AUDI_DOCUMENT_ETQ$CREATED_DATE,
DATE_FORMAT(AUDIT_DOCUMENT.ETQ$COMPLETED_DATE ,  '%b %d, %Y' ) 		AUDI_DOCUMEN_ETQ$COMPLETE_DATE,
LEFT(LOCATION_PROFILE.HIERARCHICAL_NAME , 	LOCATE(":",  LOCATION_PROFILE.HIERARCHICAL_NAME)-1)	 REGION,
"Put Audit Profile Here"  PROFILE,
APPLICABLE_AUDIT_TYPE_1.DESCRIPTION APPLICAB_AUDI_TYP_1_DESCRIPTIO

FROM
	DATACENTER.LOCATION_PROFILE LOCATION_PROFILE

LEFT JOIN
	AUDITS.ETQ$AUDIT_DOCUMENT_LOCS ETQ$AUDIT_DOCUMENT_LOCS  ON (ETQ$AUDIT_DOCUMENT_LOCS.ETQ$LOCATIONS_ID = LOCATION_PROFILE.LOCATION_PROFILE_ID )

LEFT JOIN
	AUDITS.AUDIT_DOCUMENT AUDIT_DOCUMENT  ON (AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID = ETQ$AUDIT_DOCUMENT_LOCS.AUDIT_DOCUMENT_ID )

LEFT JOIN
	LOOKUPS.APPLICABLE_AUDIT_TYPE APPLICABLE_AUDIT_TYPE_1 ON (AUDIT_DOCUMENT.APPLICABLE_ID = APPLICABLE_AUDIT_TYPE_1.APPLICABLE_AUDIT_TYPE_ID )
	
WHERE LOCATION_PROFILE.DISABLED  = 0

GROUP BY LOCATION_PROFILE.LOCATION_PROFILE_ID



**************************
AUDITS.AUDIT_PROFILE.AUDIT_TYPE  PROFILE
**************************

SELECT
AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID AUDIT_DOCUMENT_ID,
LOCATION_PROFILE.HIERARCHICAL_NAME LOCATIO_PROFIL_HIERARCHICA_NAM,
AUDIT_DOCUMENT.ETQ$CREATED_DATE AUDI_DOCUMENT_ETQ$CREATED_DATE,
AUDIT_DOCUMENT.ETQ$COMPLETED_DATE AUDI_DOCUMEN_ETQ$COMPLETE_DATE,
APPLICABLE_AUDIT_TYPE_1.DESCRIPTION APPLICAB_AUDI_TYP_1_DESCRIPTIO

FROM
AUDITS.AUDIT_DOCUMENT AUDIT_DOCUMENT

LEFT JOIN
AUDITS.ETQ$AUDIT_DOCUMENT_LOCS ETQ$AUDIT_DOCUMENT_LOCS ON (AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID = ETQ$AUDIT_DOCUMENT_LOCS.AUDIT_DOCUMENT_ID )

LEFT JOIN
DATACENTER.LOCATION_PROFILE LOCATION_PROFILE ON (ETQ$AUDIT_DOCUMENT_LOCS.ETQ$LOCATIONS_ID = LOCATION_PROFILE.LOCATION_PROFILE_ID )

LEFT JOIN
LOOKUPS.APPLICABLE_AUDIT_TYPE APPLICABLE_AUDIT_TYPE_1 ON (AUDIT_DOCUMENT.APPLICABLE_ID = APPLICABLE_AUDIT_TYPE_1.APPLICABLE_AUDIT_TYPE_ID )