SELECT
AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID AUDIT_DOCUMENT_ID,
RIGHT( 	LOCATION_PROFILE.HIERARCHICAL_NAME, 	LENGTH( LOCATION_PROFILE.HIERARCHICAL_NAME) - LOCATE(":", LOCATION_PROFILE.HIERARCHICAL_NAME) 	)	LOCATIO_PROFIL_HIERARCHICA_NAM,
DATE_FORMAT(AUDIT_DOCUMENT.ETQ$CREATED_DATE ,  '%b %d, %Y' ) 		AUDI_DOCUMENT_ETQ$CREATED_DATE,
DATE_FORMAT(AUDIT_DOCUMENT.ETQ$COMPLETED_DATE ,  '%b %d, %Y' ) 		AUDI_DOCUMEN_ETQ$COMPLETE_DATE,
LEFT(LOCATION_PROFILE.HIERARCHICAL_NAME , 	LOCATE(":",  LOCATION_PROFILE.HIERARCHICAL_NAME)-1)	 REGION,
APPLICABLE_AUDIT_TYPE_1.DESCRIPTION APPLICAB_AUDI_TYP_1_DESCRIPTIO,
AUDIT_DOCUMENT.SECTION_TITLE LOCATION_PROFILE_SECTION_TITLE,
 IF(  (SELECT COUNT(*) 
	FROM DATACENTER.LOCATION_PROFILE LP
	LEFT JOIN AUDITS.ETQ$AUDIT_DOCUMENT_LOCS ETQ$A  ON (ETQ$A.ETQ$LOCATIONS_ID = LP.LOCATION_PROFILE_ID )
	LEFT JOIN AUDITS.AUDIT_DOCUMENT AD  ON (AD.AUDIT_DOCUMENT_ID = ETQ$A.AUDIT_DOCUMENT_ID )
	LEFT JOIN LOOKUPS.APPLICABLE_AUDIT_TYPE  LOOKUP  ON (AD.APPLICABLE_ID = LOOKUP.APPLICABLE_AUDIT_TYPE_ID )
	WHERE LP.LOCATION_PROFILE_ID = LOCATION_PROFILE.LOCATION_PROFILE_ID
	AND AD.SECTION_TITLE ="2nd Quarter 2015 Base Self Assessment"
	AND AD.ETQ$CREATED_DATE>0
	AND AD.ETQ$COMPLETED_DATE>0
	)  >0, "Complete", "In Progress")
	WORKING

FROM
DATACENTER.LOCATION_PROFILE LOCATION_PROFILE

INNER JOIN
AUDITS.ETQ$AUDIT_DOCUMENT_LOCS ETQ$AUDIT_DOCUMENT_LOCS  ON (ETQ$AUDIT_DOCUMENT_LOCS.ETQ$LOCATIONS_ID = LOCATION_PROFILE.LOCATION_PROFILE_ID )

INNER JOIN
AUDITS.AUDIT_DOCUMENT AUDIT_DOCUMENT  ON (AUDIT_DOCUMENT.AUDIT_DOCUMENT_ID = ETQ$AUDIT_DOCUMENT_LOCS.AUDIT_DOCUMENT_ID )

INNER JOIN
LOOKUPS.APPLICABLE_AUDIT_TYPE APPLICABLE_AUDIT_TYPE_1 ON (AUDIT_DOCUMENT.APPLICABLE_ID = APPLICABLE_AUDIT_TYPE_1.APPLICABLE_AUDIT_TYPE_ID )

WHERE
LOCATION_PROFILE.DISABLED  = 0 AND AUDIT_DOCUMENT.SECTION_TITLE ="2nd Quarter 2015 Base Self Assessment"

GROUP BY LOCATION_PROFILE.LOCATION_PROFILE_ID