SELECT 
RVF_FORM.RVF_FORM_ID RVF_FORM_ID, 
PHASE_SETTINGS.DISPLAY_NAME PHASE_SETTINGS_DISPLAY_NAME, 
RVF_FORM.ETQ$NUMBER RVF_FORM_ETQ$NUMBER, 
RVF_FORM.EVENT_DATE_1 RVF_FORM_EVENT_DATE_1, 
REGULATORY_AGENCY_1.DESCRIPTION REGULATOR_AGENCY_1_DESCRIPTION, 
RVF_FORM.INSPECTORS RVF_FORM_INSPECTORS, 
RVF_FORM.RVF_DESCRIPTION RVF_FORM_RVF_DESCRIPTION, 
NVIS_COMP_1.DESCRIPTION NVIS_COMP_1_DESCRIPTION, 
RVF_FORM.RVF_FINDINGS RVF_FORM_RVF_FINDINGS, 
NVIS_COMP_2.DESCRIPTION NVIS_COMP_2_DESCRIPTION, 
RVF_FORM.FOLLOW_UP_DESCRIPTION RVF_FORM_FOLLOW_UP_DESCRIPTION, 
NVIS_COMP_3.DESCRIPTION NVIS_COMP_3_DESCRIPTION, 
RVF_FORM.RVF_IMPEDE_DESCRIPTION RV_FORM_RVF_IMPEDE_DESCRIPTION, 
RVF_FORM.RV_DURATION RVF_FORM_RV_DURATION, 
USER_SETTINGS_1.DISPLAY_NAME USER_SETTINGS_1_DISPLAY_NAME, 
RVF_FORM.ETQ$COMPLETED_DATE RVF_FORM_ETQ$COMPLETED_DATE, 
LEFT( RVF_INSPECTION_TYPE_1.DESCRIPTION, LOCATE( "(", RVF_INSPECTION_TYPE_1.DESCRIPTION)-1) RV_INSPECTIO_TYP_1_DESCRIPTION, 
group_concat(distinct LOCATION_PROFILE_1.HIERARCHICAL_NAME SEPARATOR '\n') LOCATI_PROFI_1_HIERARCHICA_NAM, 
group_concat(distinct RVF_1.DESCRIPTION SEPARATOR '\n') RVF_1_DESCRIPTION, 
group_concat(distinct left( LOCATION_PROFILE_1.HIERARCHICAL_NAME, locate( ":", LOCATION_PROFILE_1.HIERARCHICAL_NAME)-1) SEPARATOR '\n') RVF_FORM_DEBUG_1 

FROM 
SMS_REPORTING.RVF_FORM RVF_FORM 
LEFT JOIN 
ENGINE.PHASE_SETTINGS PHASE_SETTINGS ON (RVF_FORM.ETQ$CURRENT_PHASE = PHASE_SETTINGS.PHASE_ID ) 

LEFT JOIN 
SMS_REPORTING.ETQ$RVF_FORM_LOCS ETQ$RVF_FORM_LOCS_1 ON (RVF_FORM.RVF_FORM_ID = ETQ$RVF_FORM_LOCS_1.RVF_FORM_ID ) 

LEFT JOIN 
DATACENTER.LOCATION_PROFILE LOCATION_PROFILE_1 ON (ETQ$RVF_FORM_LOCS_1.ETQ$LOCATIONS_ID = LOCATION_PROFILE_1.LOCATION_PROFILE_ID ) 

LEFT JOIN 
LOOKUPS.REGULATORY_AGENCY REGULATORY_AGENCY_1 ON (RVF_FORM.REGULATORY_AGENCY_ID = REGULATORY_AGENCY_1.REGULATORY_AGENCY_ID ) 

LEFT JOIN 
LOOKUPS.RVF_INSPECTION_TYPE RVF_INSPECTION_TYPE_1 ON (RVF_FORM.INSPECTION_TYPE_ID = RVF_INSPECTION_TYPE_1.RVF_INSPECTION_TYPE_ID ) 

LEFT JOIN 
LOOKUPS.NVIS_COMP NVIS_COMP_1 ON (RVF_FORM.RVF_ISSUE_YN_ID = NVIS_COMP_1.NVIS_COMP_ID ) 

LEFT JOIN 
LOOKUPS.NVIS_COMP NVIS_COMP_2 ON (RVF_FORM.RVF_FOLLOW_UP_REQUIRED_ID = NVIS_COMP_2.NVIS_COMP_ID ) 

LEFT JOIN 
LOOKUPS.NVIS_COMP NVIS_COMP_3 ON (RVF_FORM.RVF_IMPEDE_ID = NVIS_COMP_3.NVIS_COMP_ID ) 

LEFT JOIN 
ENGINE.USER_SETTINGS USER_SETTINGS_1 ON (RVF_FORM.ETQ$AUTHOR = USER_SETTINGS_1.USER_ID ) 

LEFT JOIN 
SMS_REPORTING.AREAS AREAS_1 ON (RVF_FORM.RVF_FORM_ID = AREAS_1.RVF_FORM_ID ) 

LEFT JOIN 
LOOKUPS.RVF RVF_1 ON (AREAS_1.AREAS_ID = RVF_1.RVF_ID ) 

WHERE 
PHASE_SETTINGS.PHASE_TYPE IN (0,1,3) 
GROUP BY RVF_FORM.RVF_FORM_ID