SELECT LOGINS.DATES DATES,
	( select MAX(USR.FULL_CONCURRENT_USERS)
		from DATACENTER.LOGINS_BY_CONCURRENT_USERS USR
		WHERE 	YEAR(LOGINS.DATES) = YEAR(USR.DATES) 
		AND MONTH(LOGINS.DATES) =MONTH(USR.DATES) 
		AND  DAY(LOGINS.DATES) = DAY(USR.DATES)
		GROUP BY YEAR(USR.DATES), Month(USR.DATES), DAY(USR.DATES)
) MAX_USERS,
	(select  MAX(USR.READER_CONCURRENT_USERS) 
		from DATACENTER.LOGINS_BY_CONCURRENT_USERS USR
		WHERE 	YEAR(LOGINS.DATES) = YEAR(USR.DATES) 
		AND MONTH(LOGINS.DATES) =MONTH(USR.DATES)
		AND  DAY(LOGINS.DATES) = DAY(USR.DATES)
		GROUP BY YEAR(USR.DATES), Month(USR.DATES), DAY(USR.DATES)
)  MAX_READ

FROM DATACENTER.LOGINS_BY_CONCURRENT_USERS LOGINS

GROUP BY YEAR(LOGINS.DATES), Month(LOGINS.DATES), DAY(LOGINS.DATES)

